# Data Encryption and Decryption

* Data Encryption

* Encryption is a security method in which information is encoded in such a way that only authorized user can read it.It uses encryption algorithm to generate ciphertext that can only be read if decrypted.

* Data Decryption

* Decryption is the process of taking encoded or encryptedtext and converting it back into text that you (or) the computer can read and understand.

* Types

* Symmetric(Private key): It uses a single key that will be shared among the people who need to receive the message

* Asymmetric(Public key):asymmetrical encryption uses a pair of public key and a private key to encrypt and decrypt messages

* Write a function to generate key for encryption

In [1]:
# Function to generate key for encryption.
keypath = 'DataFiles/key.txt'
def generatekey(keypath):
    with open(keypath,'w') as f:
        for i in range(10):
            if i < 6:
                f.write(str(i)+ ' '+str(i+4)+'\n')
            else:
                f.write(str(i)+ ' '+str(i-6)+'\n')
    return
generatekey(keypath)

In [2]:
# Function to decrypt a DataFile
keyfile = 'DataFiles/key.txt'
def dictionarykeyFile(keyfile):
    key={}
    with open(keyfile, 'r') as f:
        for line in f:
            line =line.split()
            key[line[0]] = line[1]
    return key
def encryptMarksData(datafile, keyfile):
    # construct a dictionary for key data
    key=dictionarykeyFile(keyfile)
    with open(datafile, 'r') as f:
        filedata = f.read().split('\n')
    with open('DataFiles/encryptedMarks.txt', 'w') as f:
        for mark in filedata:
            line = ''
            for n in mark:
                line +=key[n]
            f.write(line+'\n')
    return
datafile = 'DataFiles/marks.txt'
encryptMarksData(datafile, keyfile)

In [3]:
# Function to decrypt a encrypted a File
def decryptMarksData(encryptedfile, keyfile):
    key = dictionarykeyFile(keyfile)
    newkey = {}
    for key, value in key.items():
        newkey[value] = key
    with open(encryptedfile, 'r') as f:
        encrypteddata = f.read().split('\n')
    with open('DataFiles/decryptedMarks.txt', 'w') as f:
        for encryptedmark in encrypteddata:
            line = ''
        for n in encryptedmark:
            line +=newkey[n]
            f.write(line + '\n')
    return
encryptedfile = 'DataFiles/encryptedMarks.txt'
import timeit
st = timeit.default_timer()
decryptMarksData(encryptedfile, keyfile)
print(timeit.default_timer()-st)

0.002752941000000675


In [2]:
import numpy as np
array_2d=np.array([[2,3,4],[5,8,7]])
print(array_2d)

[[2 3 4]
 [5 8 7]]


In [3]:
import numpy as np
li=[1,2,3,4,0]
a=np.array(li)
a

array([1, 2, 3, 4, 0])

for example,the following code print 1D array between 1 to 15

In [4]:
import numpy as np
a2=np.arange(10000)
a2

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [5]:
a2=np.arange(10000).reshape(100,100)
a2

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

In [7]:
 import numpy as np
    arrayu1=np.random.randint(0,2,size=(3,5))
    array1[2][2]
    print('shape')

IndentationError: unexpected indent (<ipython-input-7-5cd59dbf7ed5>, line 2)

In [8]:
import numpy as np
arr=np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [9]:
arr[::-1]

array([[10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [10]:
np.ones?

In [ ]:
a=[1,2,3]
